[package]
name = "cpp_run"
version = "0.1.0"
edition = "2021"

[dependencies]
wait-timeout = "0.2"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
tokio-util = { version = "0.7", features = ["io"] }
